# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    # tags:
    #   - "v*.*.*"
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # gh-release permission needed
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Env (Top)
        run: |
          echo "RELEASE_DATE=$(date -u +'%Y%m%d%H%M%S')" >> ${GITHUB_ENV}
          echo "RELEASE_VERSION=$(cat version)"          >> ${GITHUB_ENV}
      - name: Set Env (Tag)
        run: |
          echo "RELEASE_TAGNAME=CI/v${{ env.RELEASE_VERSION }}/${{ env.RELEASE_DATE }}" >> ${GITHUB_ENV}
      # - name: Install Deps
      #   run:
      #     sudo apt-get -y install markdown
      - name: "Free disk space"
        run: |
          bash .free-github-action-disk-space@ubuntu.sh
      - name: Build
        run: |
          echo 'building ...'
          echo "this is github.ref of ${{ github.ref }}, release tagname of ${{ env.RELEASE_TAGNAME }}"
          zip RELASE.zip README.md
      - name: "Create latest pre-release tag"
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ env.RELEASE_TAGNAME }}
          tag_exists_error: true
          no_verify_tag: false
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "CI release ${{ env.RELEASE_DATE }}"
          tag_name: ${{ env.RELEASE_TAGNAME }}
          prerelease: true
          body: "Latest pre-release on branch [${{ github.ref_name }}] in commit [${{ github.sha }}], with TagName [${{ env.RELEASE_TAGNAME }}]."
          files: |
            RELASE.zip

# Local Variables:
# tab-width: 2
# yaml-indent-offset: 2
# End:
